config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "properties#index"

  resources :properties, only: [:index, :show, :new, :create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/property.rb
class Property < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/properties_controller.rb
class PropertiesController < ApplicationController
  before_action :set_property, only: [:show]

  # GET /properties
  def index
    @properties_by_city = Property.all.group_by(&:city)
  end

  # GET /properties/1
  def show
  end

  # GET /properties/new
  def new
    @property = Property.new
  end

  # POST /properties
  def create
    @property = Property.new(property_params)

    if @property.valid?
      Ml.estimate_prices(@property)
      @property.save
      redirect_to @property, notice: 'Property was successfully created.' 
    else
      render :new 
    end
  end

  private
    def set_property
      @property = Property.find(params[:id])
    end

    def property_params
      params.require(:property)
        .permit(
          :number_of_beds,
          :number_of_bathrooms,
          :number_of_bedrooms,
          :number_of_people,
          :city
        )
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/properties_helper.rb
module PropertiesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
    <head>
        <title>PalmSpringsBnB</title>
        <%= csrf_meta_tags %>

        <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
        <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    </head>

    <body>
        <h2 style="margin-bottom: 100px">
            <%= link_to "PalmSpringsBnB", root_path %>
            <small>- Find homes in Palm Springs</small>
        </h2>
        <%= yield %>
    </body>
</html>

app/views/properties/_form.html.erb
<%= form_with(model: property, local: true) do |form| %>
    <% if property.errors.any? %>
        <div id="error_explanation">
            <h2><%= pluralize(property.errors.count, "error") %> prohibited this property from being saved:</h2>

            <ul>
                <% property.errors.full_messages.each do |message| %>
                    <li><%= message %></li>
                <% end %>
            </ul>
        </div>
    <% end %>

    <div class="field">
        <%= form.label :city %>
        <%= form.select :city, ['Palm Springs', 'N Palm Springs',
                                'Downtown Palm Springs Vacation Rentals',
                                'Palm Springs/carhedral City',
                                'Palm Springs Villas I Vacation Rentals'], id: :property_city %>
    </div>

    <div class="field">
        <%= form.label :number_of_bedrooms %>
        <%= form.select :number_of_bedrooms, (1..10), id: :property_number_of_bedrooms %>
    </div>

    <div class="field">
        <%= form.label :number_of_beds %>
        <%= form.select :number_of_beds, (1..11), id: :property_number_of_beds %>
    </div>

    <div class="field">
        <%= form.label :number_of_people %>
        <%= form.select :number_of_people, (1..15), id: :property_number_of_people %>
    </div>

    <div class="field">
        <%= form.label :number_of_bathrooms %>
        <%= form.select :number_of_bathrooms, (1..13), id: :property_number_of_bathrooms %>
    </div>

    <div class="actions">
        <%= form.submit %>
    </div>
<% end %>

app/views/properties/edit.html.erb
<h1>Editing Property</h1>

<%= render 'form', property: @property %>

<%= link_to 'Show', @property %> |
<%= link_to 'Back', properties_path %>

app/views/properties/index.html.erb
<p id="notice"><%= notice %></p>

<h1 style="margin-bottom: 80px">
    Properties

    <small>(<%= link_to "Add new", new_property_path %>)</small>
</h1>

<% @properties_by_city.each do |(city, properties)| %>
    <h3><%= city %></h3>
    <table class="properties" style="margin-bottom: 50px">
        <thead>
            <tr>
                <th>Num of <br/> Bedrooms / Beds</th>
                <th>Num of <br/> Bathrooms</th>
                <th>Max <br/> People</th>
                <th>Nightly <br/> price</th>
                <th>Weeknight <br/> price</th>
                <th>Weekend night <br/> price</th>
                <th>Weekly <br/>price</th>
                <th>Monthly <br/>price</th>
                <th colspan="3"></th>
            </tr>
        </thead>

        <tbody>
            <% properties.each do |property| %>
                <tr>
                    <td style="text-align:right">
                        <%= property.number_of_bedrooms.to_i %> /
                        <%= property.number_of_beds.to_i %>
                    </td>
                    <td style="text-align:right"><%= property.number_of_bathrooms.to_i %></td>
                    <td style="text-align:right"><%= property.number_of_people %></td>
                    <td style="text-align:right"><%= number_to_currency(property.nightly_price) %></td>
                    <td style="text-align:right"><%= number_to_currency(property.weeknight_price) %></td>
                    <td style="text-align:right"><%= number_to_currency(property.weekend_night_price) %></td>
                    <td style="text-align:right"><%= number_to_currency(property.weekly_price) %></td>
                    <td style="text-align:right"><%= number_to_currency(property.monthly_price) %></td>
                    <td><%= link_to "Show Details >>>", property %></td>
                </tr>
            <% end %>
        </tbody>
    </table>
<% end %>

<br>

app/views/properties/new.html.erb
<h1>New Property</h1>

<%= render 'form', property: @property %>

<%= link_to 'Back', properties_path %>

app/views/properties/show.html.erb
<p id="notice"><%= notice %></p>

<p style="display: inline">
    Property located in
    <h2 style="display: inline"><%= @property.city %></h2>
</p>

<br />

<p>
    <strong>Number of beds:</strong>
    <%= @property.number_of_beds.to_i %>
</p>

<p>
    <strong>Number of bathrooms:</strong>
    <%= @property.number_of_bathrooms.to_i %>
</p>

<p>
    <strong>Number of bedrooms:</strong>
    <%= @property.number_of_bedrooms %>
</p>

<p>
    <strong>Number of people:</strong>
    <%= @property.number_of_people %>
</p>

<br/>

<p>
    <strong>Pricing:</strong>

    <table class="properties">
        <tr>
            <th>Nightly <br/> price</th>
            <th>Weeknight <br/> price</th>
            <th>Weekend night <br/> price</th>
            <th>Weekly <br/>price</th>
            <th>Monthly <br/>price</th>
        </tr>
        <tr>
            <td style="text-align: right"><%= number_to_currency(@property.nightly_price) %></td>
            <td style="text-align: right"><%= number_to_currency(@property.weeknight_price) %></td>
            <td style="text-align: right"><%= number_to_currency(@property.weekend_night_price) %></td>
            <td style="text-align: right"><%= number_to_currency(@property.weekly_price) %></td>
            <td style="text-align: right"><%= number_to_currency(@property.monthly_price) %></td>
        </tr>
    </table>
</p>

<%= link_to "Back to list of Properties", properties_path %>